version: "3.8"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - /home/user/mediaserver/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - mediaserver

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - /home/user/mediaserver/config/sonarr:/config
      - /home/user/mediaserver/media/tvseries:/tv  #optional
      - /home/user/mediaserver/dls:/downloads      #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - mediaserver
    depends_on:
      - qbittorrent

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - /home/user/mediaserver/config/radarr:/config
      - /home/user/mediaserver/media/movies:/movies  #optional
      - /home/user/mediaserver/dls:/downloads       #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - mediaserver
    depends_on:
      - qbittorrent

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
      - JELLYFIN_PublishedServerUrl=http://192.168.0.5  #optional
    volumes:
      - /home/user/mediaserver/config/jellyfin:/config
      - /home/user/mediaserver/media/tvseries:/data/tvshows
      - /home/user/mediaserver/media/movies:/data/movies
      - /home/user/mediaserver/media/music:/data/music
    ports:
      - 8096:8096
      - 8920:8920       #optional
      - 7359:7359/udp   #optional
      - 1900:1900/udp   #optional
    restart: unless-stopped
    networks:
      - mediaserver

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/user/mediaserver/config/qbittorrent:/config
      - /home/user/mediaserver/dls:/downloads  #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - mediaserver

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=0
      - PGID=0
      - LOG_LEVEL=debug
      - TZ=Asia/Kolkata
      - PORT=5055  #optional
    volumes:
      - /home/user/mediaserver/config/jellyseerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped
    networks:
      - mediaserver
    depends_on:
      - jellyfin

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - /home/user/mediaserver/config/readarr:/config
      - /home/user/mediaserver/media/books:/books  #optional
      - /home/user/mediaserver/dls:/downloads      #optional
    ports:
      - 8787:8787
    restart: unless-stopped
    networks:
      - mediaserver

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    ports:
      - "8191:8191"
    restart: unless-stopped
    networks:
      - mediaserver

  # nginx:
  #   image: 'jc19/nginx-proxy-manager:latest'
  #   container_name: nginx
  #   environment:
  #     - PUID=0
  #     - PGID=0
  #     - TZ=Asia/Kolkata
  #   volumes:
  #     - /home/user/mediaserver/nginx:/data
  #     - /home/user/mediaserver/nginx/letsencrypt:/etc/letsencrypt
  #     - /home/user/mediaserver/nginx/config:/config
  #   ports:
  #     - 80:80
  #     - 81:81
  #     - 443:443
  #   restart: unless-stopped
  #   networks:
  #     - mediaserver
  # lidarr:
  #   image: lscr.io/linuxserver/lidarr:latest
  #   container_name: lidarr
  #   environment:
  #     - PUID=0
  #     - PGID=0
  #     - TZ=Asia/Kolkata
  #   volumes:
  #     - /home/user/mediaserver/config/lidarr:/config
  #     - /home/user/mediaserver/media/music:/music  #optional
  #     - /home/user/mediaserver/dls:/downloads     #optional
  #   ports:
  #     - 8686:8686
  #   restart: unless-stopped
  #   networks:
  #     - mediaserver

networks:
  mediaserver:
    driver: bridge
