services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - ~/mediaservarr/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - mediaserver

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - ~/mediaservarr/sonarr/data:/config
      - ~/mediaservarr/media/tvseries:/tv #optional
      - ~/mediaservarr/dls:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - mediaserver

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - ~/mediaservarr/radarr/data:/config
      - ~/mediaservarr/media/movies:/movies #optional
      - ~/mediaservarr/dls:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - mediaserver

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
      - JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    volumes:
      - ~/mediaservarr/jellyfin/library:/config
      - ~/mediaservarr/media/tvseries:/data/tvshows
      - ~/mediaservarr/media/movies:/data/movies
      - ~/mediaservarr/media/music:/data/music
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    networks:
      - mediaserver
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ~/mediaservarr/qbittorrent/appdata:/config
      - ~/mediaservarr/dls:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - mediaserver
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=0
      - PGID=0
      - LOG_LEVEL=debug
      - TZ=Asia/Kolkata
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - ~/mediaservarr/jellyseerr:/app/config
    networks:
      - mediaserver

    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - ~/mediaservarr/readarr/data:/config
      - ~/mediaservarr/media/books:/books #optional
      - ~/mediaservarr/dls:/downloads #optional
    ports:
      - 8787:8787
    networks:
      - mediaserver
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    ports:
      - "8191:8191"
    networks:
      - mediaserver
    environment:
      - LOG_LEVEL=info
  # nginx:
  #   image: 'jc19/nginx-proxy-manager:latest'
  #   container_name: nginx
  #   environment:
  #     - PUID=0
  #     - PGID=0
  #     - TZ=Asia/Kolkata
  #   volumes:
  #     - ~/mediaservarr/nginx:/data
  #     - ~/mediaservarr/nginx/letsencrypt:/etc/letsencrypt
  #     - ~/mediaservarr/nginx/config:/config
  #   ports:
  #     - 80:80
  #     - 81:81
  #     - 443:443
  #   networks:
  #     - mediaserver
  #   restart: unless-stopped
  # lidarr:
  #   image: lscr.io/linuxserver/lidarr:latest
  #   container_name: lidarr
  #   environment:
  #     - PUID=0
  #     - PGID=0
  #     - TZ=Asia/Kolkata
  #   volumes:
  #     - ~/mediaservarr/lidarr/config:/config
  #     - ~/mediaservarr/media/music:/music #optional
  #     - ~/mediaservarr/dls:/downloads #optional
  #   ports:
  #     - 8686:8686
  #   restart: unless-stopped
  #   networks:
  #     - mediaserver
networks:
  mediaserver:
    driver: bridge
